name: Rust CI
on:
  push:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test:
    name: Test Rust ${{matrix.toolchain}} on ${{matrix.os}}
    runs-on: ${{matrix.os}}-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain: [stable, nightly]
        os: [ubuntu] # linux-only
    steps:
      - uses: actions/checkout@master
        with:
          submodules: "true"
      - name: Get latest CMake
        uses: lukka/get-cmake@latest
      - name: configure aeronmd
        run: mkdir build && cd build && cmake -G "CodeBlocks - Unix Makefiles" ../
        working-directory: aeron
      - name: build aeronmd
        run: make aeronmd && mkdir -p $(systemd-path user-binaries) && mv ./binaries/aeronmd $(systemd-path user-binaries)
        working-directory: aeron/build
      - name: Set environment variables
        shell: bash
        run: |
          echo "$(systemd-path user-binaries)" >> $GITHUB_PATH
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{matrix.toolchain}}
          override: true
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-targets -- --test-threads=1
        env:
          RUST_LOG: "trace"
